### ISSUE TITLE
Versions  comparison ValueError

### ISSUE THREAD

**Issue by UndoGG** [AscenderTeam/AscenderFramework#12]
│ C:\Users\heyya\AppData\Local\Programs\Python\Python312\Lib\site-packages\ascender\logic\projects │
│ .py:70 in compare_versions                                                                       │
│                                                                                                  │
│    67 │   │   # Compare each component                                                           │
│    68 │   │   for c1, c2 in zip(components1, components2):                                       │
│    69 │   │   │   # Convert components to integers for comparison                                │
│ ❱  70 │   │   │   if int(c1) < int(c2):                                                          │
│    71 │   │   │   │   return -1                                                                  │
│    72 │   │   │   elif int(c1) > int(c2):                                                        │
│    73 │   │   │   │   return 1                                                                   │
│                                                                                                  │
│ ╭──────────────────────────────────────── locals ─────────────────────────────────────────╮      │
│ │          c1 = '0'                                                                       │      │
│ │          c2 = '0-beta'                                                                  │      │
│ │ components1 = ['1', '1', '0']                                                           │      │
│ │ components2 = ['1', '1', '0-beta']                                                      │      │
│ │        self = <ascender.logic.projects.UpdaterMasterLogic object at 0x0000020A3437FC80> │      │
│ │          v1 = '1.1.0'                                                                   │      │
│ │          v2 = 'v1.1.0-beta'                                                             │      │
│ ╰─────────────────────────────────────────────────────────────────────────────────────────╯      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: invalid literal for int() with base 10: '0-beta'

**Comment by Zahgrom34** [comment]
Please, address this issue to other [repository](https://github.com/AscenderTeam/AscenderCLI)
