### ISSUE TITLE
Unflexible typing in AuthenticationProvider

### ISSUE THREAD

**Issue by UndoGG** [AscenderTeam/AscenderFramework#15]
**Problem**
```
class AscenderAuthenticationFramework:
    auth_provider: AuthenticationProvider | None = None
```
auth_provider is strict AuthenticationProvider type, however, if you want to use custom auth, you will get type warning in IDE, because custom auth class is subclass of AuthenticationProvider

**Possible fix**
```
AP = TypeVar('AP', bound=AuthenticationProvider)

class AscenderAuthenticationFramework:
    auth_provider: AP | None = None
```

**Comment by Zahgrom34** [comment]
This issues is outdated as because from version v1.2.0, Ascender Framework doesn't support `AscenderAuthenticationFramework` anymore, instead it was replaced with IdentityFramework engine and we recommend you to migrate slowly to it #10
