### ISSUE TITLE
Unresolved reference in new controllers

### ISSUE THREAD

**Issue by UndoGG** [AscenderTeam/AscenderFramework#22]
![image](https://github.com/user-attachments/assets/b656fdd9-9e0b-405a-b7b4-072b571ac5ef)
![image](https://github.com/user-attachments/assets/1674f3c4-2fdc-43ce-a60f-a42f5a663f62)

**Comment by Zahgrom34** [comment]
Will be fixed in v1.2.5 soon

**Comment by Noob-A** [comment]
#34
